name: Deploy site

push:
  branches: [ "main" ]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: copy
          run: files=$(find 'frontend/.output' -type f) # get the file list
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git fetch                         # fetch branches
            git checkout build-site     # checkout to your branch
            git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
            git add -A
            git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
            git push origin frontend/.output # push to remote branch
